name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }} 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 sphinx-rtd-theme
        python -m pip install wemake-python-styleguide
        pip install -r requirements/main.txt  
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: docs/build/html/
    - name: wemake-python-styleguide
      uses: wemake-services/wemake-python-styleguide@0.14.0
      continue-on-error: true
      with:
        reporter: 'github-pr-review'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}